IaC:
  - changed-files:
    - any-glob-to-any-file: 'pulumi/**/*'

Documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - 'docs/**/*'

Scripts:
  - changed-files:
    - any-glob-to-any-file:
      - 'Scripts/**/*'
      - '*.sh'
      - '*.ps1'

Configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '*.yml'
      - '*.yaml'
      - '.**'

CI/CD:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'
