name: Publish Action
on:
  release:
    types:
       - created
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set .NET 6 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: false
      - name: Get .NET Version Information & Nuget Sources
        run: |
          dotnet nuget list source
          dotnet --version
      - name: Install Dependencies
        run: dotnet restore
      - name: Build with .NET
        run: dotnet build --force --verbosity minimal --configuration Release --no-restore
      - name: Test with .NET
        working-directory: ./NET-Core.XUnit.UnitTests
        run: dotnet test --settings "test.runsettings" --configuration Release
      - name: Publish with .NET
        run: dotnet publish --configuration Release --no-build
      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v2
        with:
            name: aspdotnet-template_publish_artifacts
            path: /home/runner/work/aspdotnet-template/aspdotnet-template/ASP.NET-Core.WebAPI/bin/Release/net5.0/publish